// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6CSGY2MEl-qY1lQEOa5Kv5pH_IKcH8Os',
    appId: '1:323741297232:web:be957f287fb8a41d15ff55',
    messagingSenderId: '323741297232',
    projectId: 'notes-docs',
    authDomain: 'notes-docs.firebaseapp.com',
    storageBucket: 'notes-docs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvSeUzVkW5r_1f7Xu-9fY4WdR1pUST6ig',
    appId: '1:323741297232:android:7259b01b6d46e69715ff55',
    messagingSenderId: '323741297232',
    projectId: 'notes-docs',
    storageBucket: 'notes-docs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYyMA8uzv82LQmQXQCPb5mw2gStvbqyG8',
    appId: '1:323741297232:ios:738a4f9a4050949815ff55',
    messagingSenderId: '323741297232',
    projectId: 'notes-docs',
    storageBucket: 'notes-docs.appspot.com',
    iosClientId: '323741297232-37fu745081bvl41vin2g5jh0vldgh8ej.apps.googleusercontent.com',
    iosBundleId: 'com.tushar.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYyMA8uzv82LQmQXQCPb5mw2gStvbqyG8',
    appId: '1:323741297232:ios:738a4f9a4050949815ff55',
    messagingSenderId: '323741297232',
    projectId: 'notes-docs',
    storageBucket: 'notes-docs.appspot.com',
    iosClientId: '323741297232-37fu745081bvl41vin2g5jh0vldgh8ej.apps.googleusercontent.com',
    iosBundleId: 'com.tushar.notes',
  );
}
